s3_bucket.py - deal gracefuly with empty bucket policy
ansible-collections/amazon.aws pull request #1368
Opened 2023-02-14 18:24 UTC by magicrobotmonkey

When using wasabi object storage, the bucket policy can be blank. This was throwing a json decode error. Fix by checking for empty string and returning None.

##### SUMMARY
Deals gracefully with empty bucket policy (encountered on wasabi storage).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
s3_bucket

##### ADDITIONAL INFORMATION
Recreate by attempting to create a new bucket on wasabi:
ENV:
S3_URL=https://s3.us-west-1.wasabisys.com

- name: create bucket
   s3_bucket:
     name: "thisbucketwillfail"

2023-02-15 08:05 UTC, tremble requested changes
Thanks for taking the time to submit this PR.  A couple of minor tweaks.

2023-02-15 08:05 UTC, tremble commented on changelogs/fragments/1368-empty_bucket_policy.yml
> +- s3_bucket - deal gracefully with empty bucket policy (i.e. from wasabi cloud storage)"
```suggestion
- s3_bucket - deal gracefully with empty bucket policy (https://github.com/ansible-collections/amazon.aws/pull/1368).
```

Changelog entries should include a link to the issue or the PR.  This helps folks dig into the what and why of a change if it's potentially significant to them

2023-02-15 12:30 UTC, magicrobotmonkey commented on plugins/modules/s3_bucket.py
> +        if(len(current_policy_string) == 0):
thanks, I've been writing too much c lately...

2023-02-15 12:34 UTC, tremble approved these changes

2023-02-15 12:55 UTC, tremble approved these changes

2023-02-15 12:55 UTC, tremble commented on changelogs/fragments/1368-empty_bucket_policy.yml
> +bugfix:
```suggestion
bugfixes:
```

2023-02-15 13:09 UTC, alinabuzachis approved these changes

2023-02-15 14:09 UTC, tremble commented
recheck

2023-02-16 14:15 UTC, tremble commented
recheck

2023-02-17 15:35 UTC, goneri commented
recheck

2023-02-17 17:16 UTC, goneri commented
recheck

2023-02-17 18:51 UTC, goneri commented
recheck

2023-02-18 07:52 UTC, merged