inventory aws_ec2 - add ssm_inventory inventory into hostvars
ansible-collections/amazon.aws pull request #1369
Opened 2023-02-15 17:13 UTC by abikouo

##### SUMMARY

using `use_ssm_inventory` users can populate hostvars with Amazon SSM inventory for configured instances
closes #704 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

`aws_ec2 inventory`

2023-02-15 19:42 UTC, gravesm commented
recheck

2023-02-16 06:53 UTC, abikouo commented
recheck

2023-02-16 16:11 UTC, abikouo commented
recheck

2023-02-17 06:20 UTC, abikouo commented
recheck

2023-03-01 13:11 UTC, alinabuzachis reviewed
@abikouo Can you also please update this guide https://github.com/ansible-collections/amazon.aws/blob/main/docs/docsite/rst/aws_ec2_guide.rst with this option?

2023-03-06 10:05 UTC, abikouo commented
> @abikouo Can you also please update this guide https://github.com/ansible-collections/amazon.aws/blob/main/docs/docsite/rst/aws_ec2_guide.rst with this option?

done!

2023-03-07 10:49 UTC, tremble requested changes

2023-03-07 10:49 UTC, tremble commented on plugins/inventory/aws_ec2.py
> +    version_added: 5.3.0
```suggestion
    version_added: 6.0.0
```

This won't cleanly backport, there's some substantial changes between 5.x and 6.x that I wasn't comfortable backporting.

2023-03-07 10:49 UTC, tremble commented on tests/integration/targets/inventory_aws_ec2/playbooks/library/test_get_ssm_inventory.py
> +module: test_get_ssm_inventory
This feels like something we should cleanup and merge into community.aws as `ssm_inventory_info`...

2023-03-07 14:43 UTC, tremble approved these changes

2023-03-07 17:26 UTC, merged

2023-03-07 17:29 UTC, tremble commented
Backporting to 5 will be complicated, I recommend not doing so, given we're less than 2 months from the planned 6.0.0 release.