ACMServiceManager.list_certificates_with_backoff: explicit key type filter added
ansible-collections/amazon.aws pull request #1570
Opened 2023-05-23 09:05 UTC by gsimon75

##### SUMMARY

Fixes #1567

[ACM.Client.list_certificates](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/acm/client/list_certificates.html#ACM.Client.list_certificates) requires explicit certificate type filter in order to return the non-RSA_2048 certificates too, and this is needed to ensure the idempotency of importing such certificates.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

acm

2023-05-23 09:16 UTC, tremble requested changes
Thanks for taking the time to submit this PR.

2 things:

1. please add a changelog fragment (https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to)
2. update the formatting to use the black code style (https://github.com/psf/black)

2023-05-23 09:16 UTC, tremble commented on plugins/module_utils/acm.py
> +                    "EC_prime256v1", "EC_secp384r1", "EC_secp521r1",
```suggestion
                    "RSA_1024",
                    "RSA_2048",
                    "RSA_3072",
                    "RSA_4096",
                    "EC_prime256v1",
                    "EC_secp384r1",
                    "EC_secp521r1",
```

With release 6 we've switched to using the black code style: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html this helps us to try and bring a more unified code style across code that's been written by a large number of contributors.

2023-05-26 16:14 UTC, alinabuzachis approved these changes

2023-06-06 09:15 UTC, tremble approved these changes

2023-06-06 09:15 UTC, tremble commented on changelogs/fragments/1567-list-certificate-all-key-types.yml
> +- acm - fixes list_certificates returning only RSA_2048 certificates
```suggestion
- module_utils.acm - fixes list_certificates returning only RSA_2048 certificates (https://github.com/ansible-collections/amazon.aws/issues/1567).
```

2023-06-06 10:42 UTC, merged