ec2_vpc_nat_gateway show fails if EIP doesn't exist
ansible-collections/amazon.aws pull request #1604
Opened 2023-06-06 21:49 UTC by taehopark32

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-06-15 18:17 UTC, jillr requested changes
The new parameter needs to be added in a couple other places.
In the DOCUMENTATION block at the top of the file (make sure to document that the default value is False) https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block

In the module [argument_spec](https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/ec2_vpc_nat_gateway.py#L858) in main(). 
 This is also where you set the default value as False.  (The types in the documentation must match the types in the arg spec, linting rules will check this)
https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec

The value of the parameter must then be assigned to a variable in this section: https://github.com/ansible-collections/amazon.aws/blob/main/plugins/modules/ec2_vpc_nat_gateway.py#L881-L892
That value would be passed to functions that need it, instead of being defined through the code.

2023-06-16 06:25 UTC, abikouo requested changes

2023-06-16 06:25 UTC, abikouo commented on plugins/modules/ec2_vpc_nat_gateway.py
> +    type: bool
```suggestion
    type: bool
    version_added: 6.2.0
```

2023-06-16 09:49 UTC, alinabuzachis commented on plugins/modules/ec2_vpc_nat_gateway.py
> +      - if EIP address is not found, create NAT gateway with EIP address as null.
I guess the description of this parameter must be carified. What happens when the users specifies an invalid allocation_id? Does default_create: True allow to still create the NAT gateway and allocate a new EIP?

Something like this:
- When I(default_create=True), if I(eip_address) is set and it is invalid or does not exist, the NAT gateway is successfully created and a new EIP is automatically allocated.
-  When I(default_create=True), if I(eip_address) is set and it is invalid or not found, the NAT gateway is successfully created and a new EIP is automatically allocated. (If this is true!!!)
- When I(default_create=False), what happens?

Please feel free to rephrase and correct my suggestions.

2023-06-16 09:52 UTC, alinabuzachis commented on changelogs/fragments/1604-c2_vpc_nat_gateway-fails-silently.yml
> +- adding a boolean parameter called default_create to allow users to have the option to choose whether they want to display an error message or create a NAT gateway when an EIP address is not found.
```suggestion
- ec2_vpc_nat_gateway - adding a boolean parameter called ``default_create`` to allow users to have the option to choose whether they want to display an error message or create a NAT gateway when an EIP address is not found. The module (ec2_vpc_nat_gateway) had incorrectly failed silently if EIP didn't exist (https://github.com/ansible-collections/amazon.aws/issues/1295).
```

2023-06-16 18:13 UTC, alinabuzachis reviewed
@taehopark32 This looks great to me if you remove the reference to the `allocation_id` since the parameter applies only to eip_address.

2023-06-16 18:13 UTC, alinabuzachis commented on plugins/modules/ec2_vpc_nat_gateway.py
> +        exist, this will fail.
If `allocation_id` is out, it does not make sense to mention it. Agreed with @gravesm! @taehopark32 Thanks for updating docs!

2023-06-16 19:19 UTC, taehopark32 commented
@alinabuzachis Thank you. I fixed the description and passed all the tests.

2023-06-21 13:47 UTC, gravesm approved these changes

2023-06-27 09:19 UTC, alinabuzachis approved these changes

2023-07-04 11:31 UTC, alinabuzachis commented
regate

2023-07-04 12:17 UTC, merged