ec2_instance: add AWSRetry.jittered_backoff on client.describe_instance_attribute
ansible-collections/amazon.aws pull request #1650
Opened 2023-07-07 12:55 UTC by tchernomax

##### SUMMARY

try to fix InvalidInstanceID.NotFound

> Could not describe attribute groupSet for instance i-…: An error occurred (InvalidInstanceID.NotFound) when calling the DescribeInstanceAttribute operation: The instance ID 'i-…' does not exist

The instance actually exists, it's just an API problem.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ec2_instance

2023-07-24 16:27 UTC, hakbailey requested changes
@tchernomax thank you for submitting this! The PR looks good but it needs a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#community-changelogs), would you be able to add that?

2023-07-24 16:45 UTC, alinabuzachis commented on plugins/modules/ec2_instance.py
> +            value = AWSRetry.jittered_backoff(
I might be wrong, but adding `InvalidInstanceID.NotFound` https://github.com/ansible-collections/amazon.aws/pull/1650/files#diff-a6b28ca5e2f98a5237ad2e88e544b3df3de7bbc95c8dc9088cae572ff92c2f60R2179 should do the job.

2023-08-12 17:06 UTC, tchernomax commented
> @tchernomax thank you for submitting this! The PR looks good but it needs a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#community-changelogs), would you be able to add that?

done

2023-08-22 23:47 UTC, hakbailey commented on changelogs/fragments/1650-fix-invalidinstanceid-notfound.yml
> +  ec2_instance - retry API call if we get `InvalidGroup.NotFound` error.
```suggestion
  ec2_instance - retry API call if we get `InvalidGroup.NotFound` error (https://github.com/ansible-collections/amazon.aws/pull/1650).
```

2023-08-27 10:31 UTC, tchernomax commented on changelogs/fragments/1650-fix-invalidinstanceid-notfound.yml
> +  ec2_instance - retry API call if we get `InvalidGroup.NotFound` error.
done

2023-09-01 15:46 UTC, alinabuzachis approved these changes

2023-09-01 16:31 UTC, hakbailey approved these changes

2023-09-01 18:36 UTC, hakbailey commented
recheck

2023-09-16 15:49 UTC, tchernomax commented
any news ?
Is there something I need to do to make this PR merged ?

2023-09-18 17:39 UTC, gravesm commented
recheck

2023-09-18 18:23 UTC, tchernomax commented
@gravesm it seems it fail at a different test at each run.

2023-09-19 13:59 UTC, tremble requested changes

2023-09-19 13:59 UTC, tremble commented on plugins/modules/ec2_instance.py
> +                client.describe_instance_status(InstanceIds=[ins["InstanceId"]], IncludeAllInstances=True)
Please leave this line as it was:

1. It's currently explicitly retrying on "InvalidInstanceID.NotFound" to deal with certain race conditions within AWS (it returns the ID, but if you quickly query that API about the ID it fails to find it)
2. Without adding `aws_retry=True` to the describe_instance_status arguments the decorator won't perform any retries.

In this case I'd leave the change you made at line 2159, but use the original code for this call, and add  `InvalidInstanceID.NotFound` to the catch_extra_error_codes parameter that was here.

2023-10-20 12:08 UTC, tremble approved these changes

2023-10-20 12:09 UTC, tremble commented
Thanks for submitting this PR.  I'm sorry it's taken so long to get this merged.

2023-10-20 13:56 UTC, merged