Prep amazon.aws 6.4.0 - release_date: '2023-09-05'
ansible-collections/amazon.aws pull request #1725
Opened 2023-09-01 15:24 UTC by alinabuzachis

##### SUMMARY

Prep amazon.aws 6.4.0 - `release_date: '2023-09-05'`

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-09-04 09:31 UTC, tremble requested changes

2023-09-04 09:31 UTC, tremble commented on changelogs/changelog.yaml
> +        module.
The ec2_key change only has a 'minor_changes' section this might cause confusion if we describe it in the release summary as a security fix.

2023-09-04 12:22 UTC, tremble approved these changes

2023-09-04 14:45 UTC, alinabuzachis commented
recheck

2023-09-05 11:38 UTC, tremble commented
regate

2023-09-05 15:43 UTC, tremble commented
The failures appear to be test flakes (and Zuul flakes), I'm going to manually merge this.

2023-09-05 15:44 UTC, merged