Include a playbook to list all Lambdas in any region
ansible-collections/amazon.aws pull request #1730
Opened 2023-09-02 17:25 UTC by theputta

##### SUMMARY
To list out all lambdas in any region 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
amazon.aws.lambda_info module 

```paste below

```

2023-09-04 13:25 UTC, abikouo approved these changes

2023-09-04 13:29 UTC, tremble requested changes
Thanks for taking the time to submit this PR.  Our examples are generally tasks rather than plays

2023-09-04 13:29 UTC, tremble commented on plugins/modules/lambda_info.py
> +
```suggestion
# List AWS Lambda Functions in a specific region 
- name: List Lambda Functions
  amazon.aws.lambda_info:
    region: us-east-1
  register: lambda_functions
- name: Display Lambda Functions
  debug:
    var: lambda_functions.functions  
```

2023-10-12 15:26 UTC, theputta commented
> Thanks for taking the time to submit this PR. Our examples are generally tasks rather than plays

@tremble I have updated as per your recommendation

2024-08-27 08:17 UTC, tremble requested changes

2024-08-27 08:17 UTC, tremble commented on plugins/modules/lambda_info.py
> +    var: lambda_functions.functions
region is applicable to almost all of our modules, we generally don't include it in examples (same as we don't include the multitude of mechanisms for passing credentials)

Generally we don't include a debug task, the examples aren't there to demo the debug builtin, and the output info has its own section of the documentation.

2024-08-27 08:18 UTC, tremble approved these changes

2024-08-27 08:18 UTC, tremble approved these changes

2024-08-27 08:18 UTC, tremble commented on plugins/modules/lambda_info.py
> +
```suggestion
```

2024-08-27 08:39 UTC, merged