DNM Migrate iam_role* modules and tests
ansible-collections/amazon.aws pull request #1760
Opened 2023-09-20 16:26 UTC by abikouo

Migrate iam_role* modules and tests

2023-09-21 08:36 UTC, tremble requested changes
Migration, +1

Deprecations/Removals:
a) I don't like pulling this into the migration PR (too much changing at once)
b) Missing breaking changelog entry
c) Last time I spoke to @alinabuzachis 7.0.0 is hopefully landing early November (to meet the Ansible 9 release deadline), since the advertised date on the deprecation was 2023-12-01, we shouldn't include this in 7.0.0

Please clean-up the "new" commits (those that weren't from community.aws).  We need to remember to manually merge with commit without squashing too.

2023-09-21 08:36 UTC, tremble commented on changelogs/fragments/migrate_iam_role.yml
> +  ``community.aws.iam_role``.
```suggestion
  ``amazon.aws.iam_role`` (https://github.com/ansible-collections/amazon.aws/pull/1760).
```

2023-09-21 08:36 UTC, tremble commented on changelogs/fragments/migrate_iam_role.yml
> +  to use ``community.aws.iam_role_info``.
```suggestion
  to use ``amazon.aws.iam_role_info`` (https://github.com/ansible-collections/amazon.aws/pull/1760).
```

2023-09-22 06:09 UTC, abikouo commented
> Migration, +1
> 
> Deprecations/Removals: a) I don't like pulling this into the migration PR (too much changing at once) b) Missing breaking changelog entry c) Last time I spoke to @alinabuzachis 7.0.0 is hopefully landing early November (to meet the Ansible 9 release deadline), since the advertised date on the deprecation was 2023-12-01, we shouldn't include this in 7.0.0
> 
> Please clean-up the "new" commits (those that weren't from community.aws). We need to remember to manually merge with commit without squashing too.

Pull request has been restricted to the code and tests migration, other (deprecation, unit tests) will follow later on another PR. The new commits have been squashed

2023-09-22 08:53 UTC, tremble approved these changes

2023-09-22 09:34 UTC, alinabuzachis approved these changes

2023-09-22 09:36 UTC, tremble requested changes

2023-09-22 09:36 UTC, tremble commented on plugins/modules/iam_role.py
> +from ansible_collections.community.aws.plugins.module_utils.modules import AnsibleAWSModule
```suggestion
from ansible_collections.amazon.aws.plugins.module_utils.modules import AnsibleAWSModule
```

2023-09-27 06:03 UTC, merged