Promote iam_mfa_device_info
ansible-collections/amazon.aws pull request #1761
Opened 2023-09-22 12:37 UTC by alinabuzachis

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-09-27 16:18 UTC, abikouo requested changes

2023-09-27 16:18 UTC, abikouo commented on plugins/modules/iam_mfa_device_info.py
> +from ansible_collections.community.aws.plugins.module_utils.modules import AnsibleCommunityAWSModule as AnsibleAWSModule
```suggestion
from ansible_collections.amazon.aws.plugins.module_utils.modules import AnsibleAWSModule
```
This is something that needs to be fixed in the `el_grande_module_promoter` repo

2023-09-28 13:30 UTC, abikouo approved these changes

2023-09-28 16:02 UTC, hakbailey requested changes

2023-09-28 16:02 UTC, hakbailey commented on meta/runtime.yml
> +    - iam_mfa_device_info
Can this be moved up so it's in alphabetical order like the others?

2023-10-02 19:42 UTC, hakbailey approved these changes

2023-10-09 12:42 UTC, merged