Add ability to remove detached internet gateway
ansible-collections/amazon.aws pull request #1786
Opened 2023-10-03 20:45 UTC by branic

##### SUMMARY

Introduces the ability to remove an internet gateway that is not attached to a VPC. To remove an internet gateway either the ID of the internet gateway or the ID of the attached VPC can be supplied. It is also possible to supply both IDs. If both IDs are supplied then a failure will be generated if the attached VPC ID does not match the user supplied VPC.

Fixes #1669 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_vpc_igw

##### ADDITIONAL INFORMATION

2023-10-04 07:20 UTC, tremble requested changes
Thanks for taking the time to submit this PR.

I've had a quick look.  The way the documentation's now worded it looks like the module should cope with attaching an existing (unattached) IGW to a VPC, which isn't the case.  I think it's worth either adding this feature or rewording the documentation.  (This might also help with #1787 since you'd at least be able to use the created IGW)

2023-10-04 07:20 UTC, tremble commented on changelogs/fragments/ec2_vpc_igw-delete_unattached-gateway.yml
> +  - Add ability to delete a vpc internet gateway using the id of the gateway
```suggestion
  - ec2_vpc_igw - Add ability to delete a vpc internet gateway using the id of the gateway (https://github.com/ansible-collections/amazon.aws/pull/1786).
```

2023-10-10 16:29 UTC, bateller approved these changes

2023-10-16 23:42 UTC, branic commented
@tremble Please review this PR again when you have a chance. I've added the ability to create an IGW without attaching a VPC to it. I also fixed #1787 and added functionality to attach/detach and change VPC attached to the internet gateway.

2023-10-30 15:37 UTC, branic commented
@tremble I just wanted to check in and see if you could review this PR again.

Thank you.

2023-10-30 16:06 UTC, tremble reviewed
Apologies for the delay, life got in the way.

Two issues:
- add version_added to docs for new paramters
- Setting force_attach and detach_vpc to True should throw an error (as early as possible) their behaviours conflict.

2023-10-30 16:06 UTC, tremble commented on plugins/modules/ec2_vpc_igw.py
> +    description:
```suggestion
    version_added: 7.0.0
    description:
```

2023-10-30 16:06 UTC, tremble commented on plugins/modules/ec2_vpc_igw.py
> +  force_attach:
```suggestion
  force_attach:
    version_added: 7.0.0
```

2023-10-30 16:06 UTC, tremble commented on plugins/modules/ec2_vpc_igw.py
> +    module = AnsibleAWSModule(argument_spec=argument_spec, supports_check_mode=True, required_if=required_if)
We should throw an error if force_attach and detach_vpc are both set

2023-10-30 16:06 UTC, tremble commented on plugins/modules/ec2_vpc_igw.py
> +  detach_vpc:
```suggestion
  detach_vpc:
    version_added: 7.0.0
```

2023-10-30 16:53 UTC, branic commented
Thanks @tremble. I totally understand life getting in the way and I appreciate you taking a look at this so quickly today. I've made the requested changes so hopefully all looks good now. If you find anything else that needs to be addressed I'm happy to do so.

2023-10-30 17:36 UTC, tremble approved these changes

2023-10-31 06:07 UTC, tremble commented
regate

2023-10-31 07:53 UTC, merged