lambda: add support for container image as alternative to runtime
ansible-collections/amazon.aws pull request #1939
Opened 2024-01-05 06:02 UTC by nethershaw

##### SUMMARY
Fixes #1417
Supersedes https://github.com/ansible-collections/amazon.aws/pull/1438

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
lambda

##### ADDITIONAL INFORMATION
The original PR appears to have been abandoned by its author. I have taken the liberty of salvaging it and resolving current merge conflicts as conservatively as possible.

I hope I have correctly merged the `required_if` and `required_together` arrays; it seems to make sense to me, and it seems to run correctly from my local library.

I have also targeted release 6.5.2 in the documentation snippet, if that is not too presumptive.

2024-01-05 08:09 UTC, tremble requested changes
While adding integration tests for this would be good, I don't think it's practical at this point since we'd need an image we could safely pull and use...

2024-01-05 08:09 UTC, tremble commented on plugins/modules/lambda.py
> +    version_added: 6.5.2
```suggestion
    version_added: 7.1.0
```

6.x is now bug/security fixes only, we can add this to 7.1 without a problem.

2024-01-05 08:09 UTC, tremble approved these changes

2024-01-05 08:21 UTC, tremble commented on plugins/modules/lambda.py
> +    code = {'ImageUri': image_uri }
```suggestion
    code = {'ImageUri': image_uri}
```

2024-01-05 08:21 UTC, tremble commented on plugins/modules/lambda.py
> +    required_by = { "runtime": "handler" }
```suggestion
    required_by = {"runtime": ["handler"]}
```

2024-01-09 11:12 UTC, alinabuzachis approved these changes
@nethershaw Only and small note, but LGTM otherwise! Thank you!

2024-01-10 09:06 UTC, merged