elb_application_lb: add support for creating alb with listener having multiple certificates
ansible-collections/amazon.aws pull request #1950
Opened 2024-01-11 16:25 UTC by mandar242

##### SUMMARY

Fixes #1349 
This PR adds support for adding multiple certificates to a listener during Application Load Balancer creation.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

elb_application_lb

##### ADDITIONAL INFORMATION

```paste below

```

2024-01-15 11:15 UTC, abikouo requested changes
@mandar242 is it possible to update the corresponding integration test case?

2024-01-15 11:15 UTC, abikouo commented on changelogs/fragments/1950-elb_application_lb-multiple-listener-certificates-for-alb.yml
> +- elb_application_lb - Add support for adding listener with multiple certificates during ALB creation (https://github.com/ansible-collections/amazon.aws/pull/1950).
I would rather prefer stating that the change in on `module_utils/elbv2` and then mention that it brings benefit for the `elb_application_elb` module

2024-01-15 11:15 UTC, abikouo commented on plugins/module_utils/elbv2.py
> +                    )
```suggestion
            listener_certificates = self.listener.get("Certificates", [])
            if len(listener_certificates) > 0:
                first_certificate, other_certs = listener_certificates[0], listener_certificates[1:]
                self.listener["Certificates"] = [first_certificate]
            # create listener
            create_listener_result = AWSRetry.jittered_backoff()(self.connection.create_listener)(
                LoadBalancerArn=self.elb_arn, **self.listener
            )
            # only one cert can be specified per call to add_listener_certificates
            for cert in other_certs:
                AWSRetry.jittered_backoff()(self.connection.add_listener_certificates)(
                    ListenerArn=create_listener_result["Listeners"][0]["ListenerArn"], Certificates=[cert]
                )
```

2024-01-16 08:42 UTC, abikouo approved these changes
LGTM

2024-01-16 12:06 UTC, alinabuzachis approved these changes

2024-01-17 22:26 UTC, mandar242 commented
recheck

2024-01-17 23:07 UTC, merged