returns boolean if a user has access to console login
ansible-collections/amazon.aws pull request #2012
Opened 2024-03-04 18:39 UTC by valkiriaaquatica

I have added that now return in the return json the parameter console_access in boolean format to know if the user has or not access to login by console to the account. It can be used in cases where you only want users to access with keys or by landing zones...

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-03-21 14:17 UTC, abikouo commented
@valkiriaaquatica thanks for your contribution to this repository.
Your PR is incomplete, you will need to add a changelog fragment describing the change, here is an example https://github.com/ansible-collections/amazon.aws/blob/main/changelogs/fragments/20231211-rds_instance_cloudwatch.yml.
You will also need to update the module `RETURN` block adding the new parameters

2024-03-21 14:25 UTC, abikouo requested changes
Just minor updates to return the full `LoginProfile` information in the output, as this should be necessary for other use cases

2024-03-21 14:25 UTC, abikouo commented on plugins/modules/iam_user_info.py
> +        return True
```suggestion
        return connection.get_login_profile(UserName=user_name)['LoginProfile']
```

2024-03-21 14:25 UTC, abikouo commented on plugins/modules/iam_user_info.py
> +            raise
```suggestion
    except is_boto3_error_code("NoSuchEntity"):
        return {}
```

2024-03-21 14:25 UTC, abikouo commented on plugins/modules/iam_user_info.py
> +        user['console_access'] = check_console_access(connection, user['UserName'])
```suggestion
        user['LoginProfile'] = check_console_access(connection, user['UserName'])
```

2024-03-21 15:31 UTC, tremble requested changes
Apologies for the significant change requests, the IAM modules have recently been subject to some refactoring work including adding decorators for some of the common error handling code.

2024-03-21 15:31 UTC, tremble commented on plugins/modules/iam_user_info.py
> +from ansible_collections.amazon.aws.plugins.module_utils.modules import AnsibleAWSModule, is_boto3_error_code
```suggestion
from ansible_collections.amazon.aws.plugins.module_utils.modules import AnsibleAWSModule
from ansible_collections.amazon.aws.plugins.module_utils.retries import AWSRetry
```

We use a single import per-line formatting standard, this helps reduce merge conflicts when multiple changes are in-flight.

2024-03-21 15:31 UTC, tremble commented on plugins/modules/iam_user_info.py
> +        return {}
```suggestion
@IAMErrorHandler.list_error_handler("get login profile", {}) 
@AWSRetry.jittered_backoff()
def check_console_access(connection, user_name):
    return connection.get_login_profile(UserName=user_name)['LoginProfile']
```

Apologies for the lack of documentation around the error handler decorator, the IAM modules are the first place they've been implemented...

2024-03-21 15:31 UTC, tremble commented on plugins/modules/iam_user_info.py
>  from ansible_collections.amazon.aws.plugins.module_utils.iam import AnsibleIAMError
```suggestion
from ansible_collections.amazon.aws.plugins.module_utils.iam import AnsibleIAMError
from ansible_collections.amazon.aws.plugins.module_utils.iam import IAMErrorHandler
```

2024-03-21 15:35 UTC, tremble commented on plugins/modules/iam_user_info.py
> +            sample: "true"
This needs updating now you return login_profile rather than console_access.

2024-03-21 18:17 UTC, valkiriaaquatica commented
thanks @abikouo  and @tremble ! If there is anythiing i can help with the iam documentation (that I see is not as complete as others)  I can help :)

2024-03-22 06:15 UTC, abikouo requested changes
Just minor change in the changelog fragment

2024-03-22 06:15 UTC, abikouo commented on changelogs/fragments/20240321-iam-user-info.yml
> +  - iam_user_info - Add console_access to return info that is get from a user, to know if they can login from AWS console (https://github.com/ansible-collections/amazon.aws/pull/2012).
```suggestion
  - iam_user_info - Add `login_profile` to return info that is get from a user, to know if they can login from AWS console (https://github.com/ansible-collections/amazon.aws/pull/2012).
```

2024-03-22 07:15 UTC, tremble approved these changes

2024-03-22 07:37 UTC, abikouo approved these changes

2024-03-22 08:52 UTC, tremble commented
@valkiriaaquatica thanks for the efforts you've put into this.  Don't worry about the docs, it's my fault and I'll get them written.  This isn't my day job so there's a certain amount of "getting around to it" involved (and everyone knows that writing code is more interesting than docs and tests :) ).

2024-03-22 09:10 UTC, merged