Create initial test suite for ec2_metadata_facts
ansible-collections/amazon.aws pull request #212
Opened 2020-12-01 23:23 UTC by jillr

##### SUMMARY
Create an instance, run metadata on the remote instance, and teardown.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/integration/targets/ec2_metadata_facts/

2020-12-01 23:26 UTC, jillr commented
@tremble This actually ended up being less hacky than I thought it would. Thoughts?

2020-12-01 23:46 UTC, jillr commented
Hrm. TODO: handle running teardown.yml even if test_initial_metadata.yml fails, ssh works on my machine but not shippable?

2020-12-02 12:36 UTC, tremble requested changes

2020-12-02 12:36 UTC, tremble commented on tests/integration/targets/ec2_metadata_facts/playbooks/test_initial_metadata.yml
> +---
We should probably add a wait_for_connection entry here.  The failure looks to be an auth failure which is likely the connection occurring before the user-data finishes running.

2020-12-02 12:36 UTC, tremble commented on tests/integration/targets/ec2_metadata_facts/runme.sh
> +
```suggestion

# Destroy Environment
cleanup() {
    ansible-playbook playbooks/teardown.yml -i inventory -c local "$@"
}

trap "cleanup" EXIT

```

(stolen from connection_aws_ssm integration tests)

2020-12-04 18:44 UTC, tremble approved these changes
LGTM

2020-12-04 18:44 UTC, merged