elb_* - Update RETURN block docs
ansible-collections/amazon.aws pull request #2151
Opened 2024-06-27 11:26 UTC by alinabuzachis

##### SUMMARY

elb_* - Update RETURN block docs

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

elb_*

##### ADDITIONAL INFORMATION

```paste below

```

2024-07-09 10:23 UTC, abikouo commented on plugins/modules/elb_application_lb.py
> +      - Indicates whether HTTP headers with invalid header fields are removed by the load balancer C(true) or routed to targets C(false).
```suggestion
      - Indicates whether HTTP headers with invalid header fields are removed by the load balancer V(true) or routed to targets V(false).
```

2024-07-09 10:32 UTC, abikouo requested changes

2024-07-09 10:32 UTC, abikouo commented on plugins/modules/elb_application_lb.py
> +            description: Information about a static IP address for a load balancer.
```suggestion
            description: Information about static IP addresses for a load balancer.
```

2024-07-09 10:32 UTC, abikouo commented on plugins/modules/elb_application_lb_info.py
> +                    description: Information about a static IP address for a load balancer.
```suggestion
                    description: Information about a static addresses for a load balancer.
```

2024-07-09 16:20 UTC, abikouo approved these changes

2024-07-15 20:37 UTC, hakbailey approved these changes

2024-07-18 12:03 UTC, merged