Add option "metadata_token_ttl_seconds" to ec2_metadata_facts module.
ansible-collections/amazon.aws pull request #2209
Opened 2024-08-01 20:31 UTC by tonyswu

##### SUMMARY
`ec2_metadata_facts` sometimes returns `401 unauthorized` if the IMDSv2 token times out. The token TTL is currently hardcoded to `60`, this pull request aims to make it configurable.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
ec2_metadata_facts

2024-08-02 07:28 UTC, tremble requested changes
Looks good as a starting point, thanks for this.  3 things:

1) Please add an integration test for the change.  The current tests for this module can be found in [tests/integration/targets/ec2_metadata_facts/playbooks/test_metadata.yml](https://github.com/ansible-collections/amazon.aws/blob/main/tests/integration/targets/ec2_metadata_facts/playbooks/test_metadata.yml)
I think this can be as simple as overwriting some of the gathered facts, running ec2_metadata_facts again with the timeout set, and then testing that the facts got updated.

2) Please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to)

3) Please add "version_added: 8.2.0" to the documentation for options (just underneath default, at the same indentation.

2024-08-02 07:28 UTC, tremble commented on plugins/modules/ec2_metadata_facts.py
> +        default: 60
```suggestion
        default: 60
        version_added: 8.2.0
```

2024-08-02 22:58 UTC, tonyswu commented
@tremble thanks for the comments, I've added integration test and changelog fragments as suggested.

2024-08-05 05:25 UTC, tremble commented on changelogs/fragments/2209-ec2_metadata_facts-add-configurable-ttl-parameter.yml
> +  - ec2_metadata_facts - Add parameter `metadata_token_ttl_seconds` (https://github.com/ansible-collections/amazon.aws/pull/2209).
```suggestion
  - ec2_metadata_facts - Add parameter ``metadata_token_ttl_seconds`` (https://github.com/ansible-collections/amazon.aws/pull/2209).
```

2024-08-05 05:42 UTC, tremble approved these changes

2024-08-05 05:42 UTC, tremble commented on plugins/modules/ec2_metadata_facts.py
> +        metadata_token_ttl_seconds=dict(required=False, default=60, type="int"),
```suggestion
        metadata_token_ttl_seconds=dict(required=False, default=60, type="int", no_log=False),
```

2024-08-05 06:43 UTC, merged