Rearrange security_token sources as AWS_SECURITY_TOKEN is deprecated
ansible-collections/amazon.aws pull request #221
Opened 2020-12-22 08:49 UTC by nillovna

##### SUMMARY

Rearranges security_token sources as AWS_SECURITY_TOKEN is deprecated.

As mentioned in [boto documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html)  `AWS_SECURITY_TOKEN` environment variable can also be considered deprecated, it is only supported for backward-compatibility purposes. So it is more logical to check `AWS_SESSION_TOKEN` before `AWS_SECURITY_TOKEN`.  Empty `AWS_SECURITY_TOKEN` could cause errors even if `AWS_SESSION_TOKEN` is defined.

Some tools already removed `AWS_SECURITY_TOKEN` support, for example, there is an issue with [saml2aws](https://github.com/Versent/saml2aws/issues/586).

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

plugins.module_utils.ec2

##### ADDITIONAL INFORMATION

Th problem is fully described in https://github.com/Versent/saml2aws/issues/586. The issue is caused by an empty `AWS_SECURITY_TOKEN`. Despite `AWS_SESSION_TOKEN` is defined ansible uses deprecated `AWS_SECURITY_TOKEN` in the first place.

2021-01-07 09:54 UTC, tremble requested changes
I'm generally in favour of this, but definitely necessitates a changelog entry.  I'd like to hear from @jill / @goneri about when it would be appropriate to merge this.

2021-01-07 10:00 UTC, Akasurde requested changes

2021-01-07 10:00 UTC, Akasurde commented on plugins/module_utils/ec2.py
> +        elif os.environ.get('AWS_SECURITY_TOKEN'):
Add a change log entry for this change.

2021-01-13 17:04 UTC, tremble commented
@jillr We might not have unit tests but we do have an integration test which tests the combination of get_aws_connection_info and connect_to_aws : https://github.com/ansible-collections/amazon.aws/blob/main/tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/credentials.yml what we don't test right now is the relative priority of EC2_SESSION_TOKEN and EC2_SECURITY_TOKEN

2021-01-13 17:12 UTC, tremble commented
@nillovna Do you think you could tweak https://github.com/ansible-collections/amazon.aws/blob/main/tests/integration/targets/module_utils_ec2/roles/connect_to_aws/tasks/credentials.yml to add a test that AWS_SESSION_TOKEN takes priority over AWS_SECURITY_TOKEN ?

2021-03-11 08:20 UTC, tremble commented
Digging into this a little further:
https://github.com/boto/botocore/blob/develop/botocore/credentials.py#L1051

It looks like our current behaviour mimics the botocore behaviour (wrt ordering)

2021-04-29 21:38 UTC, jillr commented
The next collection release of amazon.aws will be 2.0 (late May ETA), which can contain breaking changes.  Comments and test failures will need to be addressed for this to be able to merge.

2021-07-20 14:56 UTC, alinabuzachis commented
@jillr Should we put this in the Jira backlog?

2021-08-30 17:09 UTC, jillr commented
@tremble I'm ok with that. It doesn't appear to be causing any notable problems for users and avoiding breaking changes is usually desirable.

It was good to have folks that a look at this and now we know about the deprecation, thanks for raising awareness about this @nillovna! If boto3 changes the processing order and we need to revisit this we can revive the PR.

2021-08-30 17:09 UTC, closed without merging