inventory/aws2_ec2: avoid extra Display import
ansible-collections/amazon.aws pull request #226
Opened 2021-01-05 21:46 UTC by goneri

The `BaseInventoryPlugin` class already expose an instance of
`ansible.utils.display.Display`. We don't to recreate it.

2021-01-07 09:40 UTC, tremble approved these changes
The superclass does appear to include display in self, which is imported identically to the way it had been in this module.

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/__init__.py#L39
/ https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/__init__.py#L161

Change looks sane and tests pass

2021-01-07 09:41 UTC, tremble commented
@jillr / @felixfontein Do you feel this change warrants a changelog entry?

2021-01-07 11:28 UTC, felixfontein commented
@tremble good question. I tend to say "all code changes need one", to stop having to think about such cases ;-)

2021-01-07 19:33 UTC, tremble requested changes

2021-01-07 19:33 UTC, tremble commented on changelogs/fragments/226_avoid_extra_Display_import.yaml
> +- avoid an superfluous import of ansible.utils.display.Display in the ``aws_ec2`` inventory plugin
```suggestion
- aws_ec2 inventory plugin - Avoid a superfluous import of ansible.utils.display.Display 
```

2021-01-08 05:55 UTC, Akasurde commented on changelogs/fragments/226_avoid_extra_Display_import.yaml
> +- aws_ec2 inventory plugin - Avoid a superfluous import of ansible.utils.display.Display
```suggestion
- aws_ec2 inventory plugin - Avoid a superfluous import of ansible.utils.display.Display.
```

2021-01-08 06:27 UTC, Akasurde approved these changes
LGTM

2021-01-08 06:37 UTC, felixfontein commented on changelogs/fragments/226_avoid_extra_Display_import.yaml
> +- aws_ec2 inventory plugin - Avoid a superfluous import of ansible.utils.display.Display.
```suggestion
- aws_ec2 inventory plugin - avoid a superfluous import of ``ansible.utils.display.Display`` (https://github.com/ansible-collections/amazon.aws/pull/226).
```

2021-01-08 09:22 UTC, tremble approved these changes

2021-01-08 09:23 UTC, tremble commented
Thanks for tweaking the Changelog @goneri and @Akasurde

2021-01-08 09:24 UTC, merged