Add utils for ec2_placement_group
ansible-collections/amazon.aws pull request #2322
Opened 2024-10-04 15:04 UTC by GomathiselviS

##### SUMMARY

This PR adds utils for ec2_placement_group

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-10-04 15:38 UTC, abikouo requested changes

2024-10-04 15:38 UTC, abikouo commented on changelogs/fragments/add_utils_ec2_placement_group.yml
> +  - module_utils/ec2 - add utils for the ec2_placement_group* modules.
```suggestion
  - module_utils/ec2 - add utils for the ec2_placement_group* modules (https://github.com/ansible-collections/amazon.aws/pull/2322).
```

2024-10-04 15:38 UTC, abikouo commented on plugins/module_utils/ec2.py
> +    client.delete_placement_group(**params)
```suggestion
def delete_placement_group(client, group_name: str) -> bool:
    client.delete_placement_group(GroupName=group_name)
```
The `GroupName` parameter is required to delete the placement group

2024-10-04 15:38 UTC, abikouo commented on plugins/module_utils/ec2.py
> +    return client.create_placement_group(**params)["PlacementGroups"]
```suggestion
    return client.create_placement_group(**params)["PlacementGroup"]
```

2024-10-08 15:29 UTC, alinabuzachis approved these changes
I'm not sure if it makes sense to use DryRun. I would probably use check_mode without passing DryRun, but I would also like to know what @tremble thinks about.

2024-10-09 11:05 UTC, abikouo requested changes

2024-10-09 11:05 UTC, abikouo commented on plugins/module_utils/ec2.py
> +    client.delete_placement_group(GroupName=group_name, DryRun=dry_run)
```suggestion
def delete_ec2_placement_group(client, group_name: str) -> bool:
    client.delete_placement_group(GroupName=group_name)
```
we are not using `dry_run` to run the check mode

2024-10-09 11:05 UTC, abikouo commented on plugins/module_utils/errors.py
> +                    return {"boto3_error_code": "DryRunOperation"}
```suggestion
```

2024-10-09 17:19 UTC, GomathiselviS commented
> I'm not sure if it makes sense to use DryRun. I would probably use check_mode without passing DryRun, but I would also like to know what @tremble thinks about.

I've currently removed it. From my assessment based on the definition of check_mode, the API should not be invoked at all. Moreover, DryRun is utilized across various AWS APIs beyond just placement groups. Given that other modules haven't implemented it, it seemed logical to exclude the DryRun functionality from this particular module.

2024-10-11 20:47 UTC, merged