DNM Migrate elb_classic_lb_info modules and tests
ansible-collections/amazon.aws pull request #2350
Opened 2024-10-21 21:34 UTC by mandar242

##### SUMMARY

DNM Migrate elb_classic_lb_info modules and tests
Refer : https://issues.redhat.com/browse/ACA-1179

elb_classic_lb is already in amazon.aws

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-10-22 13:55 UTC, GomathiselviS requested changes

2024-10-22 13:55 UTC, GomathiselviS commented on plugins/modules/elb_classic_lb_info.py
> +version_added: 1.0.0
version_added_collection: community.aws

2024-10-22 13:55 UTC, GomathiselviS commented on tests/integration/targets/elb_classic_lb_info/tasks/main.yml
> +    elb_classic_lb:
Use FQCN

2024-10-22 13:55 UTC, GomathiselviS commented on tests/integration/targets/elb_classic_lb_info/tasks/main.yml
> +  - assert:
Use FQCN for all module calls.

2024-10-22 17:25 UTC, GomathiselviS approved these changes

2024-10-23 11:05 UTC, alinabuzachis approved these changes

2024-10-24 15:18 UTC, merged