remove instance-state-name inverse filters in favor of standard value…
ansible-collections/amazon.aws pull request #237
Opened 2021-01-14 18:41 UTC by IamNobleSix

remove instance-state-name inverse filters in favor of standard value filters on other 4 accepted options to fix bad aws return

##### SUMMARY

This fixes: https://github.com/ansible-collections/amazon.aws/issues/235

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

amazon aws ec2.py

##### ADDITIONAL INFORMATION
Instead of using inverse filters (which to my knowledge are not allowed by any or all version of aws cli and can cause issues as noted in https://github.com/ansible-collections/amazon.aws/issues/235) use the other 4 allowed values as normal outlined in https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instances.html for instance-state-name

2021-01-15 13:57 UTC, gravesm requested changes
Thank you for the PR, @IamNobleSix. This change looks good. We need a changelog fragment before we can merge: https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment.

It would also be a good idea to add a test for this, which would have caught this regression before it went out. In this case, I think just adding a task to stop the second instance here: https://github.com/ansible-collections/amazon.aws/blob/main/tests/integration/targets/ec2/tasks/main.yml#L138 and then assert that it is in fact stopped should be sufficient.

2021-01-15 14:19 UTC, IamNobleSix commented
Hi @gravesm that sounds good to me. I will get working on that today. Thanks.

2021-01-18 19:09 UTC, IamNobleSix commented
Stop test created using similar logic to already established terminate test on line 103.

2021-01-19 13:37 UTC, gravesm approved these changes
Thanks for your work on this, @IamNobleSix!

2021-01-22 19:48 UTC, goneri approved these changes

2021-01-22 19:48 UTC, jillr approved these changes

2021-01-22 19:49 UTC, goneri commented
Thank you @IamNobleSix for your contribution.

2021-01-22 19:49 UTC, merged