ec2_vol: preset the name tag of the volume
ansible-collections/amazon.aws pull request #242
Opened 2021-01-15 21:41 UTC by goneri

Depends-On: https://github.com/ansible-collections/amazon.aws/pull/241

Closes: https://github.com/ansible-collections/amazon.aws/issues/229

2021-01-18 17:50 UTC, goneri commented
note: Tests need https://github.com/ansible-collections/amazon.aws/pull/241 to pass

2021-01-20 22:33 UTC, jillr approved these changes
Thanks @goneri!

2021-01-21 08:04 UTC, tremble requested changes
We specifically want to know that we're not breaking the Name tag or removing tags that we didn't try to set.

I have a preference that we'd expose a "purge_tags" option rather than hard coding either.  But I'm good with that being a separate PR (that I'd be willing to raise)

2021-01-21 08:04 UTC, tremble commented on tests/integration/targets/ec2_vol/tasks/tests.yml
>          volume_type: gp2
```suggestion
        volume_type: gp2
        name: '{{ resource_prefix }} - sdh'
```

2021-01-21 08:04 UTC, tremble commented on tests/integration/targets/ec2_vol/tasks/tests.yml
> +          - new_vol_attach_result.volume.tags["snake_case"] == 'simple_snake_case'
```suggestion
          - new_vol_attach_result.volume.tags["snake_case"] == 'simple_snake_case'
          - new_vol_attach_result.volume.tags["Name"] == '{{ resource_prefix }} - sdh'          
```

2021-01-21 13:47 UTC, goneri commented
> We specifically want to know that we're not breaking the Name tag or removing tags that we didn't try to set.
> 
> I have a preference that we'd expose a "purge_tags" option rather than hard coding either. But I'm good with that being a separate PR (that I'd be willing to raise)

I would prefer to ask the user to use [ec2_tag](https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_tag_module.html) instead.

2021-01-21 13:55 UTC, tremble commented
https://docs.ansible.com/ansible/latest/dev_guide/platforms/aws_guidelines.html#dealing-with-tags

```
It is common practice in Ansible AWS modules to have a purge_tags parameter that defaults to true.

The purge_tags parameter means that existing tags will be deleted if they are not specified by the Ansible task.
```

I think we should chose something and be consistent, updating the doc above to reflect this.

The advantage of having the module manage tagging shows up during creation of resources, since it lets you identify them from creation.  If we're letting people manage tags on creation it makes sense to have a consistent interface that lets them manage them during the whole lifecycle.

2021-02-19 17:17 UTC, jillr commented on plugins/modules/ec2_vol.py
> +    version_added: 1.4.0
1.4 shipped last week so this will need to be 2.0 (I don't currently expect a 1.5)

2021-02-19 17:35 UTC, tremble requested changes
Apologies if I'm failing to spot it, I don't see an integration test for `purge_tags: True`

2021-02-19 17:35 UTC, tremble commented on plugins/modules/ec2_vol.py
> +    description: Whether to remove existing tags that aren't passed in the C(tags) parameter
```suggestion
    description: Whether to remove existing tags that aren't passed in the I(tags) parameter
```

2021-02-19 17:35 UTC, tremble commented on tests/integration/targets/ec2_vol/tasks/tests.yml
> +          - new_vol_attach_result.volume.tags["snake_case"] == 'simple_snake_case ❤️'
Still think we should explicitly check here that we didn't change Name

2021-03-11 20:05 UTC, tremble requested changes

2021-03-11 20:19 UTC, tremble approved these changes

2021-03-12 05:44 UTC, merged