route53_zone - Add support for enabling DNSSEC signing in a specific hosted zone
ansible-collections/amazon.aws pull request #2421
Opened 2024-12-11 10:37 UTC by alinabuzachis

##### SUMMARY

route53_zone - Add support for enabling DNSSEC signing in a specific hosted zone

Will rebase once https://github.com/ansible-collections/amazon.aws/pull/2412 is merged.

Closes https://github.com/ansible-collections/amazon.aws/issues/1976

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

route53_zone

##### ADDITIONAL INFORMATION

```paste below

```

2025-01-07 09:05 UTC, abikouo requested changes

2025-01-07 09:05 UTC, abikouo commented on plugins/modules/route53_zone.py
> +    return response
```suggestion
        return client.get_dnssec(HostedZoneId=zone_id)
    except (BotoCoreError, ClientError) as e:
        module.fail_json_aws(e, msg=f"Could not get DNSSEC for {zone_id}")
```

2025-01-07 09:05 UTC, abikouo commented on plugins/modules/route53_zone.py
> +    if dnssec is True:
```suggestion
    if dnssec:
```

2025-01-07 09:05 UTC, abikouo commented on plugins/modules/route53_zone.py
> +    elif dnssec is False:
```suggestion
    else:
```

2025-01-07 09:05 UTC, abikouo commented on plugins/modules/route53_zone.py
> +                    module.fail_json_aws(e, msg=f"Could not enable DNSSEC for {zone_id}")
can you move this to a dedicated function?

2025-01-07 09:05 UTC, abikouo commented on plugins/modules/route53_zone.py
> +                    module.fail_json_aws(e, msg=f"Could not enable DNSSEC for {zone_id}")
can you move this to a dedicated function?

2025-01-15 14:03 UTC, alinabuzachis commented on plugins/modules/route53_zone.py
> +                    module.fail_json_aws(e, msg=f"Could not enable DNSSEC for {zone_id}")
Done!

2025-01-15 14:03 UTC, alinabuzachis commented on plugins/modules/route53_zone.py
> +                    module.fail_json_aws(e, msg=f"Could not enable DNSSEC for {zone_id}")
Done!

2025-01-16 12:21 UTC, abikouo approved these changes

2025-01-16 12:21 UTC, abikouo commented on plugins/modules/route53_zone.py
> +        # DNSSEC signing is in the process of being removed for the hosted zone.
```suggestion
```

2025-01-16 17:25 UTC, alinabuzachis commented on plugins/modules/route53_zone.py
> +        # DNSSEC signing is in the process of being removed for the hosted zone.
I added these comments to document what's happening if dnssec_status == "DELETING":.

2025-01-17 09:27 UTC, merged