s3: raise an error if the bucket name is not correct
ansible-collections/amazon.aws pull request #341
Opened 2021-04-26 18:07 UTC by goneri

Ensure the name of the bucket does not go above 63 characters.

See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

2021-04-26 18:21 UTC, jillr approved these changes

2021-04-26 19:22 UTC, goneri commented
recheck

2021-04-26 20:57 UTC, goneri commented
recheck

2021-04-27 18:56 UTC, goneri commented
recheck

2021-04-28 05:16 UTC, tremble requested changes
Mostly looks good

2021-04-28 05:16 UTC, tremble commented on plugins/module_utils/s3.py
> +        module.fail_json(msg='the following characters are invalid in a bucket name: %s' % illegal_characters)
Is it worth listing which characters **are** valid?

2021-04-28 05:16 UTC, tremble commented on tests/integration/targets/aws_s3/tasks/main.yml
> +
We generally use "assert" rather than failed_when

2021-05-04 14:23 UTC, tremble approved these changes

2021-05-04 21:29 UTC, merged