Add support for ipv6 addresses
ansible-collections/amazon.aws pull request #430
Opened 2021-08-02 21:24 UTC by abhattacharyaNS1

##### SUMMARY
Allow amazon.aws.aws_service_ip_ranges to return only IPv6 addresses with setting ipv6_prefix=True

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
amazon.aws.aws_service_ip_ranges 

##### ADDITIONAL INFORMATION

```
vars:
  rt53_ranges: "{{ lookup('aws_service_ip_ranges', region='us-west-2', service='ROUTE53_HEALTHCHECKS', ipv6_prefix=True, wantlist=True) }}"
tasks:

- name: "use list return option and iterate as a loop"
  debug: msg="{% for x in rt53_ranges %}{{ x }} {% endfor %}"
# "2600:1f14:7ff:f800::/56,2600:1f14:fff:f800::/56"
```

2021-08-09 20:06 UTC, abhattacharyaNS1 reviewed
Removed formatting changes

2021-08-10 09:46 UTC, tremble requested changes
Thanks for taking the time to raise this PR.

The kwargs logic currently looks a little broken.  I've added some suggestions as to how to fix this.

If possible please also add some integration tests.  There are currently two examples of integration tests for lookups:
- https://github.com/ansible-collections/amazon.aws/tree/main/tests/integration/targets/lookup_aws_account_attribute
- https://github.com/ansible-collections/amazon.aws/tree/main/tests/integration/targets/lookup_aws_secret

It would be really good if these tests could test 
- unlimited lookup
- limiting by region
- limiting by service
- limiting by region and service
- setting ipv6_prefix(es) to True
- setting ipv6_prefix(es) to False

I'd recommend just checking that the returned values are valid ipv4/ipv6 CIDRs, since we have no guarantees what IP addresses Amazon would use.

2021-08-10 09:46 UTC, tremble commented on plugins/lookup/aws_service_ip_ranges.py
> +    description: 'Return only ipv6 addresses. Option: ipv6_prefix=True'
```suggestion
  ipv6_prefixes:
    description: 'Return only ipv6 addresses. Option: ipv6_prefixes=True'
```

2021-08-10 09:46 UTC, tremble commented on plugins/lookup/aws_service_ip_ranges.py
> +            ip_prefix_label = "ipv6_prefix"
The logic here looks a little broken.  I'd suggest tweaking it a little:

```suggestion
        if "ipv6_prefix" in kwargs and kwargs["ipv6_prefix"]:
            prefixes_label = "ipv6_prefixes"
            ip_prefix_label = "ipv6_prefix"
        else:
            prefixes_label = "prefixes"
            ip_prefix_label = "ip_prefix"
```

2021-08-10 09:47 UTC, tremble commented
Integration tests are simply an Ansible role in the tests/integration/targets directory named after the module being tested (lookups are prefixed with `lookup_`.

2021-08-10 09:52 UTC, tremble commented
We also need a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2021-08-10 19:57 UTC, gravesm commented
recheck

2021-09-06 10:05 UTC, alinabuzachis commented
recheck

2021-09-08 03:27 UTC, abhattacharyaNS1 commented
> Hi @abhattacharyaNS1 sorry I needed to drop off IRC the other day.
> 
> I've just added some initial (ipv4 only) integration tests for the aws_service_ip_ranges lookup plugin (#473) I expect them to merge in the next hour or so. Please would you add some ipv6 prefix tests at the end. Don't change the existing ones, we need to know that existing behaviour isn't broken.
> 
> With regards testing that things are IPv4/IPv6 addresses I suspect you misunderstood what I was referring to when I was talking about "testing" that things are IP addresses. Rather than testing the IP addresses in the module, adding an additional dependency to the plugin, which would probably count as a breaking change since it's not already required by the collection, simply add integration tests that check that the IP addresses are IPv6 addresses, ie, that someone's not introduced a bug and is returning values from the "prefixes" section of the document instead of the ipv6_prefixes section.

Now I understand! I will update the test case and push a new update! 
Thanks

2021-09-08 03:28 UTC, abhattacharyaNS1 commented
recheck

2021-09-11 05:58 UTC, tremble reviewed
Some minor tweaks

2021-09-11 05:58 UTC, tremble commented on tests/integration/targets/lookup_aws_service_ip_ranges/tasks/main.yaml
> +  set_fact:    no_params: "{{ lookup('amazon.aws.aws_service_ip_ranges') }}"
```suggestion
  set_fact:
    no_params: "{{ lookup('amazon.aws.aws_service_ip_ranges') }}"
```

2021-09-11 05:58 UTC, tremble commented on tests/integration/targets/lookup_aws_service_ip_ranges/tasks/main.yaml
> +
```suggestion
  - name: lookup IPV6 range with region
    set_fact:
      us_east_1_ipv6s: "{{ lookup('amazon.aws.aws_service_ip_ranges', region='us-east-1', wantlist=True, ipv6_prefixes=True) }}"

```

2021-09-11 05:58 UTC, tremble commented on plugins/lookup/aws_service_ip_ranges.py
> +    description: 'Return only ipv6 addresses. Option: ipv6_prefixes=True'
```suggestion
    description: 'Return only ipv6 addresses. Option: ipv6_prefixes=True'
    version_added: 2.0.0
```

2021-09-13 18:28 UTC, abhattacharyaNS1 commented
@tremble Thanks for the fix! Please let me know if there is anything else i need to add to this PR.

2021-09-16 06:39 UTC, tremble requested changes
Mostly niggles, I'll merge these, if they pass CI we can get it into main.

2021-09-16 06:39 UTC, tremble commented on tests/integration/targets/lookup_aws_service_ip_ranges/tasks/main.yaml
> +    want_ipv6_list: "{ lookup('amazon.aws.aws_service_ip_ranges', wantlist=True, ipv6_prefixes=True) }}"
```suggestion
    want_ipv6_list: "{{ lookup('amazon.aws.aws_service_ip_ranges', wantlist=True, ipv6_prefixes=True) }}"
```

2021-09-16 09:15 UTC, tremble approved these changes

2021-09-16 11:09 UTC, merged