[DNM] test EE tests
ansible-collections/amazon.aws pull request #432
Opened 2021-08-03 05:55 UTC by Akasurde

##### SUMMARY

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
zuul.yaml

2021-08-03 08:47 UTC, Akasurde commented
recheck

2021-08-03 09:30 UTC, Akasurde commented
recheck

2021-08-10 09:00 UTC, tremble commented
@Akasurde Please can we rename these jobs "network-ee" is misleading.  Something like "ansible-ee-" would be better.

2021-08-11 06:19 UTC, Akasurde commented
@tremble This is an already written job and shared by multiple teams. So I think @pabelanger is the right person to answer this.

2021-08-14 14:35 UTC, pabelanger commented
@Akasurde @tremble We can rename them, but we need to bikeshed on the format.  This is a test EE, so we likly should rename to test-ee however, it will be work to do so.

2021-08-14 14:36 UTC, pabelanger requested changes

2021-08-14 14:36 UTC, pabelanger commented on requirements.txt
> +netaddr
These requirements should be removed now, and retested.

2021-08-16 11:51 UTC, pabelanger commented
recheck

2021-08-16 11:51 UTC, pabelanger commented
Sorry, I caused a bug in the docker jobs over the weekend this is now fixed by: https://github.com/ansible/ansible-zuul-jobs/pull/1062

2021-08-16 12:04 UTC, pabelanger commented
Added https://github.com/ansible/ansible-zuul-jobs/pull/1046 too

2021-08-16 12:04 UTC, pabelanger commented
recheck

2021-08-16 12:42 UTC, pabelanger commented
failure looks to be network related

2021-08-16 12:42 UTC, pabelanger commented
recheck

2021-08-16 14:31 UTC, closed without merging