ec2_group: update documentation for specifying port ranges
ansible-collections/amazon.aws pull request #436
Opened 2021-08-03 23:07 UTC by mandar242

##### SUMMARY

Added missing part of documentation for specifying port ranges as ```-1``` value in parameter ```from_port``` and ```to_port``` is only supported for ```proto:icmp```. 

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ec2_group

2021-08-04 04:25 UTC, markuman approved these changes
LGTM

2021-08-04 13:41 UTC, alinabuzachis approved these changes
Thank you @mandar242. LGTM as well.

2021-08-05 09:41 UTC, tremble requested changes
Thanks for taking the time to submit this PR.

A minor formatting niggle: the numbers should be wrapped in C() since they're values.
I'd also recommend splitting the description lines up rather than having one big line.

The ec2_group CI tests are currently broken, I've added a Depends-on against the PR which will disable the integration tests.  Since this only touches the docs we just need the CI test suites not to fail.

2021-08-05 09:41 UTC, tremble commented on plugins/modules/ec2_group.py
> +            description: The start of the range of ports that traffic is coming from. A value can be between 0 to 65535. A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```suggestion
            description:
            - The start of the range of ports that traffic is coming from.
            - A value can be between C(0) to C(65535).
            - A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```

2021-08-05 09:41 UTC, tremble commented on plugins/modules/ec2_group.py
> +            description: The end of the range of ports that traffic is coming from. A value can be between 0 to 65535. A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```suggestion
            description:
            - The end of the range of ports that traffic is coming from.
            - A value can be between C(0) to C(65535).
            - A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```

2021-08-05 09:41 UTC, tremble commented on plugins/modules/ec2_group.py
> +            description: The start of the range of ports that traffic is going to. A value can be between 0 to 65535. A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```suggestion
            description:
            - The start of the range of ports that traffic is going to.
            - A value can be between C(0) to C(65535).
            - A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```

2021-08-05 09:41 UTC, tremble commented on plugins/modules/ec2_group.py
> +            description: The end of the range of ports that traffic is going to. A value can be between 0 to 65535. A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```suggestion
            description:
            - The end of the range of ports that traffic is going to.
            - A value can be between C(0) to C(65535).
            - A value of C(-1) indicates all ports (only supported when I(proto=icmp)).
```

2021-08-05 17:35 UTC, mandar242 commented
> Thanks for taking the time to submit this PR.
> 
> A minor formatting niggle: the numbers should be wrapped in C() since they're values.
> I'd also recommend splitting the description lines up rather than having one big line.
> 
> The ec2_group CI tests are currently broken, I've added a Depends-on against the PR which will disable the integration tests. Since this only touches the docs we just need the CI test suites not to fail.

Thank you for the feedback.

2021-08-05 17:38 UTC, tremble approved these changes

2021-08-05 21:27 UTC, jillr commented
recheck

2021-08-09 07:35 UTC, tremble commented
recheck

2021-08-09 11:23 UTC, tremble commented
recheck

2021-08-09 17:15 UTC, merged