Adding example of using groups in aws_ec2.py module
ansible-collections/amazon.aws pull request #458
Opened 2021-08-11 20:16 UTC by mandar242

##### SUMMARY
Adding a example of using ```groups``` option to add items from a specific inventory configuration to groups.
Example shows use of ```groups``` to group hosts based on ```vpc id```.

Resolves #412 

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME

aws_ec2.py

2021-08-16 20:01 UTC, goneri requested changes
Thanks @mandar242.

2021-08-16 20:01 UTC, goneri commented on plugins/inventory/aws_ec2.py
> +  - tag:Name
The `hostnames` block is already covered in some other examples and this is not what you want to demonstrate. You can just remove the key and stick with the default value.

2021-08-18 15:35 UTC, alinabuzachis approved these changes

2021-08-19 06:34 UTC, Akasurde approved these changes

2021-08-23 17:26 UTC, goneri approved these changes

2021-08-24 10:08 UTC, alinabuzachis commented
recheck

2021-08-24 10:58 UTC, merged