[WIP] Prepare 2.0.0 release
ansible-collections/amazon.aws pull request #489
Opened 2021-09-03 22:10 UTC by jillr

##### SUMMARY
Prepare 2.0.0 release.  Run add_docs, generate changelog, update versions

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
amazon.aws

2021-09-07 17:50 UTC, tremble commented
Looks like there might be something wrong with the ec2_eni_info markup?

```
2021-09-03 22:33:13.906380 | centos-8-stream | ERROR: docs/amazon.aws.ec2_eni_info_module.rst:481:0: Explicit markup ends without a blank line; unexpected unindent.
```

2021-09-09 22:37 UTC, jillr commented
> Looks like there might be something wrong with the ec2_eni_info markup?
> 
> ```
> 2021-09-03 22:33:13.906380 | centos-8-stream | ERROR: docs/amazon.aws.ec2_eni_info_module.rst:481:0: Explicit markup ends without a blank line; unexpected unindent.
> ```

Yeah add_docs.py does something funky and I just haven't taken the time to figure it out.  I just manually add the extra indentations.

2021-09-10 05:23 UTC, tremble commented
> Yeah add_docs.py does something funky and I just haven't taken the time to figure it out. I just manually add the extra indentations.

could be an add_docs bug, ec2_eni_info looks like the only amazon.aws module where version_added is used in RETURN

2021-09-10 20:57 UTC, jillr commented
I think ec2_spot_request_info will take a few more days to merge and I don't want to block the release. If it merges fast I'll do a quick refresh of this PR.

ready_for_review

2021-09-11 06:05 UTC, tremble commented
@jillr The one remaining change I'd like to see prior to 2.0.0 is #488 it's got the various approvals and just needs gating but given the scope I'd prefer a member of your team do the final gating.

2021-09-13 17:01 UTC, jillr commented
> @jillr The one remaining change I'd like to see prior to 2.0.0 is #488 it's got the various approvals and just needs gating but given the scope I'd prefer a member of your team do the final gating.

@tremble I'm fine with that if we can get it through.  I haven't had a chance to dig into the CI failures, is it just the ec2_metadata change you PRed?

2021-09-13 17:06 UTC, tremble commented
> I'm fine with that if we can get it through. I haven't had a chance to dig into the CI failures, is it just the ec2_metadata change you PRed?

Yeah the metadata PR and some timeouts which (as far as I can tell) are cause by too many things in one bucket.

2021-09-15 14:27 UTC, alinabuzachis commented
@jillr FYI
```
ERROR: Found 1 rstcheck issue(s) which need to be resolved:
ERROR: docs/amazon.aws.ec2_eni_info_module.rst:481:0: Explicit markup ends without a blank line; unexpected unindent.
See documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/rstcheck.html
```

2021-09-15 19:02 UTC, goneri commented
recheck

2021-09-15 19:02 UTC, tremble requested changes

2021-09-15 19:03 UTC, jillr commented on CHANGELOG.rst
> +- amazon.aws collection - The amazon.aws collection has dropped support for ``botocore<1.16.0`` and ``boto3<1.13.0``. Most modules will continue to work with older versions of the AWS SDK, however co
I must have missed it because --refresh-fragments is throwing an error.  I'll get that sorted asap

2021-09-15 19:03 UTC, goneri commented on CHANGELOG.rst
> +- amazon.aws collection - The amazon.aws collection has dropped support for ``botocore<1.16.0`` and ``boto3<1.13.0``. Most modules will continue to work with older versions of the AWS SDK, however co
It would be nice if `antsibull-changelog` was able to regenerate the last entry if we call it a second time with fixed changelog fragment.

2021-09-15 19:12 UTC, tremble commented on CHANGELOG.rst
> +- amazon.aws collection - Due to the AWS SDKs announcing the end of support for Python less than 3.6 (https://boto3.amazonaws.com/v1/documentation/api/1.17.64/guide/migrationpy3.html) this collection
```suggestion
```

manually remove this line?

2021-09-15 19:45 UTC, tremble approved these changes

2021-09-15 21:32 UTC, merged