ec2_vpc_endpoint use module_utils helper for tagging
ansible-collections/amazon.aws pull request #525
Opened 2021-10-04 17:39 UTC by alinabuzachis

##### SUMMARY

- `ec2_vpc_endpoint` use module_utils helper for tag management

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_vpc_endpoint

2021-10-04 17:45 UTC, tremble requested changes
Generally looks good, but as with nat gateway it's now possible to pass TagSpecifications during creation (since botocore 1.14.11)

2021-10-04 17:46 UTC, alinabuzachis commented
> Generally looks good, but as with nat gateway it's now possible to pass TagSpecifications during creation (since botocore 1.14.11)

@tremble Thanks. I didn't check that, sorry. I'll update accordingly.

2021-10-05 10:52 UTC, tremble commented on plugins/modules/ec2_vpc_endpoint.py
> +
```suggestion

```

2021-10-05 10:53 UTC, tremble approved these changes

2021-10-05 12:04 UTC, tremble commented on plugins/modules/ec2_vpc_endpoint.py
> +from ansible_collections.amazon.aws.plugins.module_utils.ec2 import ensure_ec2_tags
```suggestion
from ansible_collections.amazon.aws.plugins.module_utils.ec2 import ensure_ec2_tags
from ansible_collections.amazon.aws.plugins.module_utils.ec2 import ansible_dict_to_boto3_tag_list
```

2021-10-05 16:09 UTC, merged