ec2_vpc_endpoint: improve documentation to provide details about route_table_ids
ansible-collections/amazon.aws pull request #613
Opened 2022-01-13 19:26 UTC by mandar242

##### SUMMARY

Modify documentation to specify that while creating VPC endpoint using ```ec2_vpc_endpoint```, route table IDs are only valid for ```gateway``` type endpoints.
As specified in the API doc:
```
RouteTableIds (list) --
(Gateway endpoint) One or more route table IDs.
```

Fixes #576 
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

ec2_vpc_endpoint
##### ADDITIONAL INFORMATION

API Doc: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_vpc_endpoint

2022-01-17 10:49 UTC, alinabuzachis requested changes

2022-01-17 10:49 UTC, alinabuzachis commented on plugins/modules/ec2_vpc_endpoint.py
> +      - Route table ids are only valid for gateway type endpoints.
I would also add a check for this. Maybe something like: 

```
if vpc_endpoint_type != 'Gateway' and route_table_ids:
    add a warn message like "Route table ids are only valid for gateway type endpoints.  route_table_id are ignored. 
```

cc @tremble

2022-01-17 14:40 UTC, alinabuzachis approved these changes

2022-01-20 21:22 UTC, jillr approved these changes

2022-01-20 22:22 UTC, merged