Fix/support envvars for lookup aws ssm
ansible-collections/amazon.aws pull request #623
Opened 2022-01-18 18:08 UTC by Cicatrice

##### SUMMARY

Working on support in `lookup` plugin `amazon.aws.aws_ssm` for `endpoint` parameters, as well of tradional environment variable for client configuration (`AWS_PROFILE`, `AWS_ACCESS_KEY_ID`, ...).

This should fixes #519 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`amazon.aws.aws_ssm`

##### ADDITIONAL INFORMATION

It seems `LookupModule` cannot benefit from `AnsibleAWSModule` (it expect several methods/params, I am not familiar enough with Python and Ansible to sort it out) ; so this PR uses `boto3_conn` and `get_aws_connection_info` defined in `utils.ec2`.

This is a simple snippet how it can be used:
```yaml
- name: Load env
  collections:
  - amazon.aws
  gather_facts: no
  hosts: localhost
  connection: local
  vars:
    my_env: "{{ lookup('amazon.aws.aws_ssm', 'status', endpoint='http://localhost:4566') }}"
  tasks:
    - name: show the env
      debug:
        msg: "{{ my_env }}"

```

Command line test:
```bash
ANSIBLE_COLLECTIONS_PATHS=${ANSIBLE_HOME}/collections ansible-playbook test.yml
```

Output:
```
PLAY [Load env] *************************************************************************************************************************************************************************************************************************************************************

TASK [show the env] *********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "INIT"
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Another test with envars:
```bash
AWS_ACCESS_KEY_ID='foo' AWS_ACCESS_SECRET_KEY='bar' AWS_URL='http://localhost:4566' ANSIBLE_COLLECTIONS_PATHS=${ANSIBLE_HOME}/collections ansible-playbook test.yml
```
where we remove the `endpoint` from `lookup`:
```yaml
- name: Load env
  collections:
  - amazon.aws
  gather_facts: no
  hosts: localhost
  connection: local
  vars:
    my_env: "{{ lookup('amazon.aws.aws_ssm', 'status') }}"
  tasks:
    - name: show the env
      debug:
        msg: "{{ my_env }}"
```

(provides same output)

2022-01-18 23:51 UTC, Cicatrice commented
recheck

2022-01-19 10:11 UTC, Cicatrice commented
recheck

2022-02-01 13:55 UTC, Cicatrice commented
recheck

2022-02-17 10:08 UTC, alinabuzachis commented
recheck

2022-03-21 11:37 UTC, markuman commented on plugins/lookup/aws_ssm.py
> +    type: string
```suggestion
    type: string
    version_added: 3.2.0
```

2022-03-21 11:37 UTC, markuman commented
recheck

2022-03-21 11:38 UTC, markuman commented
@Cicatrice can you also add a channgelog fragment please?

2022-03-23 10:09 UTC, alinabuzachis commented
recheck

2022-03-23 13:01 UTC, alinabuzachis commented
recheck

2022-03-23 16:06 UTC, alinabuzachis commented
recheck

2022-03-28 07:15 UTC, alinabuzachis commented
recheck

2022-03-28 10:42 UTC, abikouo commented
recheck

2022-05-19 15:02 UTC, alinabuzachis commented
@Cicatrice Could you please rebase your branch?

2022-05-19 15:02 UTC, alinabuzachis commented
@Cicatrice Could you please rebase your branch?

2022-05-19 15:03 UTC, alinabuzachis commented on plugins/lookup/aws_ssm.py
> +    type: string
`version_added: 3.4.0`

2022-05-24 09:13 UTC, alinabuzachis commented
@Cicatrice could you also please add a changelog fragment for this fix https://cn-ansibledoc.readthedocs.io/zh_CN/latest/community/development_process.html#changelogs? Thank you.

2022-05-24 09:13 UTC, alinabuzachis commented
@Cicatrice could you also please add a changelog fragment for this fix https://cn-ansibledoc.readthedocs.io/zh_CN/latest/community/development_process.html#changelogs? Thank you.

2022-05-24 13:05 UTC, tremble requested changes
Thanks for taking the time to submit this PR.
2 minor things:

1) Please add a changelog fragment https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to
2) boto3_conn already catches the various botocore exceptions, there's no need to re-catch them.

2022-05-25 12:26 UTC, closed without merging