Update ec2_instance find_instances to fix incompatibility with Python 3.8
ansible-collections/amazon.aws pull request #767
Opened 2022-04-02 18:43 UTC by Razique

##### SUMMARY

Update ec2_instance find_instances to use temporary dict. instead of inline changes. Fixes #709

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

`ec2_instance`

##### ADDITIONAL INFORMATION
Current `ec2_module` iterates over a filters dictionary to perform hyphen to underscore substitution while popping keys in the process. This is not compatible with Python 3.8. I have simply created a second dictionary, I can also create a shallow copy via the `copy()` module if the team prefers.

2022-04-05 09:41 UTC, abikouo approved these changes
LGTM!!

2022-04-05 09:44 UTC, alinabuzachis commented
recheck

2022-04-05 09:44 UTC, alinabuzachis approved these changes

2022-04-05 09:48 UTC, tremble requested changes
Thanks Razique, one minor issue

2022-04-05 09:48 UTC, tremble commented on plugins/modules/ec2_instance.py
> +                sanitized_filters[key.replace("_", "-")] = filters[key]
Needs an "else" to ensure that tag based filters are also added to the list of sanitized filers

2022-04-13 12:14 UTC, alinabuzachis commented
recheck

2022-04-22 11:01 UTC, tremble approved these changes

2022-04-25 08:26 UTC, tremble commented
regate

2022-04-26 22:43 UTC, jillr commented
regate

2022-05-03 08:47 UTC, alinabuzachis commented
regate

2022-05-03 10:03 UTC, merged