Prep 3.3.0 release
ansible-collections/amazon.aws pull request #842
Opened 2022-05-26 13:40 UTC by alinabuzachis

##### SUMMARY

Run add_docs, generate changelog

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

several

2022-05-26 14:28 UTC, jatorcasso requested changes
tiny typo and duplicate line changes

2022-05-26 14:28 UTC, jatorcasso commented on CHANGELOG.rst
> +- module_utils - add new aliases ``aws_session_token`` and ``session_token`` to the ``security_token`` paramater to be more in-line with the boto SDK (https://github.com/ansible-collections/amazon.aw
```suggestion
- module_utils - add new aliases ``aws_session_token`` and ``session_token`` to the ``security_token`` parameter to be more in-line with the boto SDK (https://github.com/ansible-collections/amazon.aws/pull/631).
```

2022-05-26 14:28 UTC, jatorcasso commented on CHANGELOG.rst
> +- aws_account_attribute lookup plugin - fix linting errors in documentation data (https://github.com/ansible-collections/amazon.aws/pull/701).
```suggestion

```

2022-05-26 14:28 UTC, jatorcasso commented on changelogs/changelog.yaml
> +        data (https://github.com/ansible-collections/amazon.aws/pull/701).
```suggestion

```

2022-05-26 14:28 UTC, jatorcasso commented on changelogs/changelog.yaml
> +        to the ``security_token`` paramater to be more in-line with the boto SDK (https://github.com/ansible-collections/amazon.aws/pull/631).
```suggestion
        to the ``security_token`` parameter to be more in-line with the boto SDK (https://github.com/ansible-collections/amazon.aws/pull/631).
```

2022-05-26 19:21 UTC, alinabuzachis commented
> tiny typo and duplicate line changes

@jatorcasso Thank you!

2022-05-26 20:02 UTC, jatorcasso approved these changes
LGTM!

2022-05-27 06:14 UTC, markuman approved these changes

2022-05-27 07:58 UTC, tremble approved these changes

2022-05-30 09:35 UTC, merged