ec2_instance: metadata_options version_added increased
ansible-collections/amazon.aws pull request #852
Opened 2022-05-31 18:10 UTC by markuman

##### SUMMARY
After CI troubles in the past, we've forget to backport this feature.

* incr from 3.2.0 to 3.3.0 https://github.com/ansible-collections/amazon.aws/pull/763
* initial implementation for 3.2.0 https://github.com/ansible-collections/amazon.aws/pull/715

therefore no changelog fragment is necessary.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

ec2_instance

##### ADDITIONAL INFORMATION

```paste below

```

2022-06-07 18:52 UTC, alinabuzachis approved these changes

2022-06-13 07:54 UTC, tremble requested changes
CI isn't accepting the backport.  With 4.0.0 so close let's cut our losses and call this a 4.0.0 feature.

2022-06-13 07:54 UTC, tremble commented on plugins/modules/ec2_instance.py
> +        version_added: 3.4.0
```suggestion
        version_added: 4.0.0
```

2022-06-13 07:54 UTC, tremble commented on plugins/modules/ec2_instance.py
> +        version_added: 3.4.0
```suggestion
        version_added: 4.0.0
```

2022-06-13 07:54 UTC, tremble commented on plugins/modules/ec2_instance.py
> +        version_added: 3.4.0
```suggestion
        version_added: 4.0.0
```

2022-06-22 13:59 UTC, merged