fix ignore_nonexistent_bucket bug for listing (#966)
ansible-collections/amazon.aws pull request #967
Opened 2022-08-11 12:19 UTC by akiuni

##### SUMMARY
remove duplicated use of bucket_check() and reuse bucketrtn instead 
Fixes #966 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
s3_object

##### ADDITIONAL INFORMATION

2022-08-11 12:27 UTC, tremble requested changes
Thanks for taking the time to submit this PR.

The change looks sensible, and I'm not sure we can cleanly test the behaviour in CI.  However, it would be good if you could include a changelog fragment: https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2022-08-11 13:29 UTC, tremble commented
@akiuni please create a changelog *fragment* file.  the main changelog.yml file is updated as part of our release process

https://docs.ansible.com/ansible/latest/community/development_process.html#changelogs-how-to

2022-08-12 07:06 UTC, tremble commented on changelogs/fragments/966-ignore_nonexistent_bucket_list.yml
> +- s3_object - fix ignore_nonexistent_bucket is not used when listing a bucket (https://github.com/ansible-collections/amazon.aws/issues/966).
```suggestion
- s3_object - also use ``ignore_nonexistent_bucket`` when listing a bucket (https://github.com/ansible-collections/amazon.aws/issues/966).
```

2022-08-12 07:06 UTC, tremble approved these changes

2022-08-12 09:18 UTC, akiuni commented
[ This test is failing ](https://github.com/ansible-collections/community.aws/blob/9660de0304b256c56075f3f20b627b9d47706b44/tests/integration/targets/acm_certificate/tasks/main.yml#L508) , I don't see why but it prevents the checks from being successful

2022-08-12 13:17 UTC, tremble commented
recheck

2022-08-12 13:30 UTC, tremble commented
@akiuni I suspect this is a quirk of the way we identify cross-repo impacts (a change to the ACM utility code landed yesterday) I've asked it to re-run the tests, if they still fail I'll try rebasing your change

2022-08-12 13:47 UTC, akiuni commented
Thx for your answer, it worked fine :) now waiting for ansible gate I suppose

2022-08-12 14:01 UTC, tremble commented
@akiuni the "gate" tests are used for the final merge, I was waiting for the tests to pass before triggering them.

2022-08-12 14:20 UTC, merged