Cleanup doc_fragments/aws.py
ansible-collections/amazon.aws pull request #985
Opened 2022-08-30 13:21 UTC by alinabuzachis

##### SUMMARY

Allow to pull the requirements from `aws_boto3.py` doc fragments instead of from `aws.py`.
This also allows collections importing docs fragments from amazon.aws to use their own boto3, botocore and python requirements.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-08-30 13:27 UTC, tremble commented
Note: This would technically be a breaking change, and as such shouldn't be backported.

2022-08-30 13:29 UTC, tremble requested changes
Generally in favour of the change, however the developer docs also need updated:

https://github.com/ansible-collections/amazon.aws/blob/main/docs/docsite/rst/dev_guidelines.rst#common-documentation-fragments-for-connection-parameters

2022-09-13 11:41 UTC, alinabuzachis commented
> Generally in favour of the change, however the developer docs also need updated:
> 
> https://github.com/ansible-collections/amazon.aws/blob/main/docs/docsite/rst/dev_guidelines.rst#common-documentation-fragments-for-connection-parameters

@tremble done, thanks!

2022-09-13 14:50 UTC, alinabuzachis commented
recheck

2022-09-13 18:57 UTC, jillr approved these changes

2022-09-13 18:58 UTC, tremble approved these changes

2022-09-13 18:59 UTC, gravesm commented on docs/docsite/rst/dev_guidelines.rst
Github won't let me put this comment on a line you didn't change, but two lines above this "There are two" should probably be updated to say "There are four".

2022-09-13 19:32 UTC, goneri approved these changes

2022-09-27 11:28 UTC, alinabuzachis commented
recheck

2022-09-27 14:40 UTC, alinabuzachis commented
recheck

2022-09-28 17:12 UTC, alinabuzachis commented
recheck

2022-09-28 18:50 UTC, alinabuzachis commented
recheck

2022-09-28 20:57 UTC, jillr commented
recheck

2022-09-29 08:44 UTC, alinabuzachis commented
recheck

2022-09-29 08:49 UTC, tremble commented
Will probably still fail.  The inventory tests take about 45 minutes.

This might help:
https://github.com/ansible-collections/amazon.aws/pull/1070/files#diff-797630fda5cc98086f92121dd44832753fb831ff7ef40616b1ac8f2436f03f65

2022-09-29 11:10 UTC, tremble commented
recheck

2022-09-29 11:16 UTC, tremble commented
recheck

2022-09-29 12:46 UTC, tremble commented
recheck

2022-09-29 15:48 UTC, alinabuzachis commented
recheck

2022-09-29 18:45 UTC, alinabuzachis commented
recheck

2022-09-29 21:39 UTC, alinabuzachis commented
recheck

2022-09-30 08:23 UTC, alinabuzachis commented
recheck

2022-09-30 12:36 UTC, merged